import json
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from backend.services.analytics import get_traffic_density
import os

def generate_pdf_report(stats_record: dict, output_path: str):
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "TrafficVision AI - Professional Report")
    
    # Separation
    c.setLineWidth(1)
    c.line(50, height - 60, width - 50, height - 60)
    
    total = stats_record.get("total_vehicles", 0)
    density = get_traffic_density(total)
    
    c.setFont("Helvetica", 14)
    c.drawString(50, height - 100, f"Total Vehicles Detected: {total}")
    c.drawString(50, height - 120, f"Traffic Density: {density['level']}")
    
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 160, "Vehicle Distribution:")
    
    c.setFont("Helvetica", 12)
    y = height - 190
    counts = stats_record.get("counts", {})
    for v_type, count in counts.items():
        c.drawString(70, y, f"- {v_type}: {count}")
        y -= 20
        
    c.setFont("Helvetica", 10)
    c.drawString(50, 50, "Generated by TrafficVision AI System")
    
    c.save()

def generate_json_report(stats_record: dict, output_path: str):
    with open(output_path, "w") as f:
        json.dump(stats_record, f, indent=4)
